scoreboard objectives add lv dummy
scoreboard objectives add hp dummy
scoreboard objectives add maxhp dummy
scoreboard objectives add xp dummy
scoreboard objectives add nxp dummy
scoreboard objectives add money dummy
scoreboard objectives add atk dummy
scoreboard objectives add def dummy
scoreboard objectives add matk dummy
scoreboard objectives add mdef dummy
scoreboard objectives add vit dummy
scoreboard objectives add agi dummy
scoreboard objectives add hit dummy
scoreboard objectives add point dummy
scoreboard objectives add mp dummy
scoreboard objectives add maxmp dummy
scoreboard objectives add rx dummy
scoreboard objectives add ry dummy
scoreboard objectives add rz dummy
scoreboard objectives add zokusei dummy
scoreboard objectives add hasxp dummy
scoreboard objectives add killc dummy
scoreboard objectives add guildname dummy
scoreboard objectives add guildmoney dummy
scoreboard objectives add guildxp dummy
scoreboard objectives add playerguild dummy
scoreboard objectives add guildmoneyper dummy
scoreboard objectives add guildxpper dummy
scoreboard objectives add px dummy
scoreboard objectives add py dummy
scoreboard objectives add pz dummy