scoreboard players set @a lv 1
scoreboard players set @a hp 1000
scoreboard players set @a maxhp 1000
scoreboard players set @a xp 0
scoreboard players set @a nxp 100
scoreboard players set @a money 1
scoreboard players set @a atk 1
scoreboard players set @a def 1
scoreboard players set @a matk 1
scoreboard players set @a mdef 1
scoreboard players set @a vit 1
scoreboard players set @a agi 1
scoreboard players set @a hit 1
scoreboard players set @a point 1
scoreboard players set @a mp 100
scoreboard players set @a maxmp 100
scoreboard players set @a rx 1
scoreboard players set @a ry 1
scoreboard players set @a rz 1
scoreboard players set @a zokusei 1
scoreboard players set @a hasxp 1
scoreboard players set @a killc 0
scoreboard players set @a guildname 1
scoreboard players set @a guildmoney 1
scoreboard players set @a guildxp 1
scoreboard players set @a playerguild 1
scoreboard players set @a guildmoneyper 1
scoreboard players set @a guildxpper 1